# Generated by Django 2.1.7 on 2019-04-03 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='mail',
            field=models.CharField(default='', max_length=32),
        ),
    ]
