# Generated by Django 2.1.7 on 2019-04-03 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20190403_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='mail',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='phone',
            field=models.CharField(default=0, max_length=128),
        ),
    ]
