# Generated by Django 2.1.7 on 2019-04-03 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20190403_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='user_type',
            field=models.IntegerField(choices=[(0, '普通用户'), (1, 'VIP')], default=0),
        ),
    ]
