# Generated by Django 2.1.7 on 2019-04-04 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_userwordsnum'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userwordsnum',
            old_name='WordsNum',
            new_name='wordsnum',
        ),
    ]
