# Generated by Django 2.1.7 on 2019-04-07 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_basewords'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookname', models.CharField(max_length=64)),
                ('author', models.CharField(max_length=64)),
                ('press', models.CharField(default='', max_length=64)),
                ('isbn', models.CharField(default='', max_length=64)),
                ('recommendrank', models.IntegerField(default=0, max_length=16)),
            ],
        ),
    ]
