# Generated by Django 2.1.7 on 2019-04-12 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20190411_0723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='sex',
            field=models.IntegerField(choices=[(0, '男生'), (1, '女生'), (2, '一位不方便透露性别的人')], default=0),
        ),
    ]
