# Generated by Django 2.1.7 on 2019-04-12 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20190412_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendbook',
            name='image',
            field=models.CharField(default='', max_length=540),
        ),
        migrations.AddField(
            model_name='recommendbook',
            name='summary',
            field=models.CharField(default='', max_length=1280),
        ),
    ]
