# Generated by Django 2.1.7 on 2019-04-12 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20190412_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendbook',
            name='image',
            field=models.CharField(default='', max_length=320),
        ),
    ]
