# Generated by Django 2.1.7 on 2019-04-12 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20190412_1554'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recommendbook',
            old_name='press',
            new_name='publisher',
        ),
        migrations.RenameField(
            model_name='recommendbook',
            old_name='bookname',
            new_name='title',
        ),
    ]
