# Generated by Django 2.1.7 on 2019-04-13 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20190412_1614'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendbook',
            name='image',
        ),
        migrations.AddField(
            model_name='recommendbook',
            name='limage',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='recommendbook',
            name='mimage',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='recommendbook',
            name='simage',
            field=models.CharField(default='', max_length=128),
        ),
    ]
