# Generated by Django 2.1.7 on 2019-04-13 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_doubanbook'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doubanbook',
            name='recommendrank',
        ),
    ]
