# Generated by Django 2.1.7 on 2019-04-13 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_remove_doubanbook_recommendrank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doubanbook',
            name='author',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='doubanbook',
            name='rating',
            field=models.IntegerField(default=0, max_length=16),
        ),
        migrations.AlterField(
            model_name='doubanbook',
            name='title',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='doubanbook',
            name='votes',
            field=models.IntegerField(default=0, max_length=16),
        ),
    ]
