# Generated by Django 2.1.7 on 2019-04-13 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20190413_0753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doubanbook',
            name='author',
        ),
        migrations.RemoveField(
            model_name='doubanbook',
            name='isbn',
        ),
        migrations.RemoveField(
            model_name='doubanbook',
            name='limage',
        ),
        migrations.RemoveField(
            model_name='doubanbook',
            name='mimage',
        ),
        migrations.RemoveField(
            model_name='doubanbook',
            name='publisher',
        ),
        migrations.RemoveField(
            model_name='doubanbook',
            name='simage',
        ),
        migrations.RemoveField(
            model_name='doubanbook',
            name='summary',
        ),
    ]
