# Generated by Django 2.1.7 on 2019-04-13 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20190413_0808'),
    ]

    operations = [
        migrations.AddField(
            model_name='doubanbook',
            name='author',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='doubanbook',
            name='isbn',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='doubanbook',
            name='limage',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='doubanbook',
            name='mimage',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='doubanbook',
            name='publisher',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='doubanbook',
            name='simage',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='doubanbook',
            name='summary',
            field=models.CharField(default='', max_length=1280),
        ),
    ]
