# Generated by Django 2.1.7 on 2019-04-13 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_auto_20190413_0819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doubanbook',
            name='summary',
            field=models.CharField(default='', max_length=2560),
        ),
    ]
