# Generated by Django 2.1.7 on 2019-04-13 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_auto_20190413_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doubanbook',
            name='summary',
            field=models.CharField(default='', max_length=3840),
        ),
    ]
