# Generated by Django 2.1.7 on 2019-04-13 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_timegap'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timegap',
            old_name='wordsnum',
            new_name='lasttime',
        ),
    ]
