# Generated by Django 2.1.7 on 2019-04-13 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_auto_20190413_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='timegap',
            name='eight',
            field=models.IntegerField(default=0, max_length=16),
        ),
        migrations.AddField(
            model_name='timegap',
            name='five',
            field=models.IntegerField(default=0, max_length=16),
        ),
        migrations.AddField(
            model_name='timegap',
            name='four',
            field=models.IntegerField(default=0, max_length=16),
        ),
        migrations.AddField(
            model_name='timegap',
            name='nine',
            field=models.IntegerField(default=0, max_length=16),
        ),
        migrations.AddField(
            model_name='timegap',
            name='one',
            field=models.IntegerField(default=0, max_length=16),
        ),
        migrations.AddField(
            model_name='timegap',
            name='seven',
            field=models.IntegerField(default=0, max_length=16),
        ),
        migrations.AddField(
            model_name='timegap',
            name='six',
            field=models.IntegerField(default=0, max_length=16),
        ),
        migrations.AddField(
            model_name='timegap',
            name='ten',
            field=models.IntegerField(default=0, max_length=16),
        ),
        migrations.AddField(
            model_name='timegap',
            name='three',
            field=models.IntegerField(default=0, max_length=16),
        ),
        migrations.AddField(
            model_name='timegap',
            name='two',
            field=models.IntegerField(default=0, max_length=16),
        ),
    ]
