# Generated by Django 2.1.7 on 2019-04-19 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userwordhistory',
            name='time',
            field=models.IntegerField(default=0, max_length=16),
        ),
    ]
