# Generated by Django 2.1.7 on 2019-04-24 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ocr_api', '0005_auto_20190424_0814'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userwordhistory',
            old_name='word',
            new_name='wordinfo',
        ),
    ]
