# Generated by Django 2.1.7 on 2019-04-26 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ocr_api', '0006_auto_20190424_0830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userwordhistory',
            name='wordinfo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tool.Word'),
        ),
    ]
