# Generated by Django 2.1.7 on 2019-04-19 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('author', models.CharField(max_length=64)),
                ('publisher', models.CharField(default='', max_length=64)),
                ('isbn', models.CharField(default='', max_length=64)),
                ('summary', models.CharField(default='', max_length=1280)),
                ('simage', models.CharField(default='', max_length=128)),
                ('mimage', models.CharField(default='', max_length=128)),
                ('limage', models.CharField(default='', max_length=128)),
                ('recommendrank', models.IntegerField(default=0, max_length=16)),
            ],
        ),
    ]
