# Generated by Django 2.1.7 on 2019-04-20 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_api', '0003_auto_20190419_1121'),
    ]

    operations = [
        migrations.CreateModel(
            name='KidsBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(default='', max_length=64)),
                ('title', models.CharField(default='', max_length=64)),
                ('author', models.CharField(default='', max_length=64)),
                ('publisher', models.CharField(default='', max_length=64)),
                ('summary', models.CharField(default='', max_length=1280)),
                ('simage', models.CharField(default='', max_length=128)),
                ('mimage', models.CharField(default='', max_length=128)),
                ('limage', models.CharField(default='', max_length=128)),
            ],
        ),
    ]
