# Generated by Django 2.1.7 on 2019-04-20 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_api', '0004_kidsbook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kidsbook',
            name='summary',
            field=models.CharField(default='', max_length=3200),
        ),
    ]
