# Generated by Django 2.1.7 on 2019-04-21 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_api', '0006_timegap'),
    ]

    operations = [
        migrations.AddField(
            model_name='kidsbook',
            name='rating',
            field=models.FloatField(default=0, max_length=16),
        ),
        migrations.AddField(
            model_name='kidsbook',
            name='votes',
            field=models.IntegerField(default=0, max_length=16),
        ),
    ]
