# Generated by Django 2.1.7 on 2019-04-24 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_api', '0008_auto_20190421_0808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendbook',
            name='recommendrank',
            field=models.IntegerField(default=0, max_length=16),
        ),
    ]
