# Generated by Django 2.1.7 on 2019-04-17 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.IntegerField(choices=[(0, '普通用户'), (1, 'VIP')], default=0)),
                ('username', models.CharField(max_length=32, unique=True)),
                ('password', models.CharField(max_length=64)),
                ('phone', models.CharField(default=0, max_length=128)),
                ('mail', models.CharField(default='', max_length=256)),
                ('sex', models.IntegerField(choices=[(0, '男生'), (1, '女生'), (2, '一位不方便透露性别的人')], default=0)),
                ('age', models.IntegerField(default=0, max_length=32)),
            ],
        ),
    ]
