# Generated by Django 2.1.7 on 2019-04-17 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usr_api', '0002_usertoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=12)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='usr_api.UserInfo')),
            ],
        ),
    ]
