# Generated by Django 2.1.7 on 2019-04-17 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usr_api', '0003_passwordcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=22)),
                ('code', models.CharField(max_length=12)),
            ],
        ),
        migrations.RemoveField(
            model_name='passwordcode',
            name='user',
        ),
        migrations.DeleteModel(
            name='PasswordCode',
        ),
    ]
