# Generated by Django 2.1.7 on 2019-04-18 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usr_api', '0004_auto_20190417_1352'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseWords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='UserWordsNum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wordsnum', models.IntegerField(default=0, max_length=32)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='usr_api.UserInfo')),
            ],
        ),
    ]
