# Generated by Django 2.1.7 on 2019-04-23 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=16)),
                ('gif', models.CharField(default='', max_length=128)),
                ('pinyin', models.CharField(default='', max_length=128)),
                ('bihua', models.CharField(default='', max_length=16)),
                ('bushou', models.CharField(default='', max_length=16)),
                ('yisi1', models.CharField(default='', max_length=640)),
                ('yisi2', models.CharField(default='', max_length=640)),
                ('yisi3', models.CharField(default='', max_length=640)),
            ],
        ),
    ]
