# Generated by Django 2.1.7 on 2019-04-28 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usr_api', '0004_auto_20190417_1352'),
        ('tool', '0002_word'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestTimeGap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='usr_api.UserInfo')),
            ],
        ),
    ]
