# Generated by Django 2.1.7 on 2019-04-28 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0003_requesttimegap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requesttimegap',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
